### ISSUE TITLE
چرا شماره‌هایی مثل ۱۱۱۱۱۱۱۱۱۱ حذف شده‌اند؟

### ISSUE THREAD

**Issue by ahangarha** [mhfeizi/yii2-iranian-national-code-validator#1]
<div dir=rtl>
سلام

در بخشی از کد، تمام شماره‌هایی که ارقام یکسان دارند نامعتبر شناخته می‌شود. چرا؟‌ دلیل خاصی دارد؟ آیا اطمینانی وجود دارد که این شماره‌ها معتیر نیستند؟

https://github.com/mhfeizi/yii2-iranian-national-code-validator/blob/5f16ea58a3433ba2f69bc88e18179fffd04e63aa/Validator.php#L46

**Comment by mhfeizi** [comment]
سلام
کد ملی با رقم های یکسان معتبر نیست. البته مثل این که ده تا یک معتبر هست که باگ مربوط به اون رفع شده و می تونین آخرین نسخه رو دانلود کنین.
تو سایت مربوط به یارانه هم کدش اومده
http://www.refahi.ir/assets/compressed/js_default_92efd086_2359bbe0_198453c8.php

**Comment by ahangarha** [comment]
<div dir=rtl>
اشتباه بدی بود. خوبه که اصلاح شد
